DELETE FROM toc;
DELETE FROM book;
INSERT INTO toc(title) VALUES('第一章 为何我信');
INSERT INTO book(chapter,verse,content) VALUES(1,1,'一个年轻人用一万元买了一枚钻石戒指，装在珠宝商送的小盒子里，送给他的未婚妻。几天后，未婚妻对他说：“亲爱的，你送给我的小盒子十分精致漂亮，我会好好地保管它，把它放在一个很安全的地方，不让它受损。”这年轻人听了一定会很失望。这故事听起来是不是很可笑？可是同样的，有许多人宁愿花费大把时间和精力去照顾身体，却不关心里面的灵魂；只照顾外在的躯壳，却忽略了里面真正的宝贝——灵魂，这不也是很可笑吗？');
INSERT INTO book(chapter,verse,content) VALUES(1,2,'《圣经》告诉我们，人死后，肉体归为尘土，但灵魂却永远存在，它的价值是无限的。');
INSERT INTO book(chapter,verse,content) VALUES(1,3,'美国诗人郎费罗 (Longfellow) 这样写道：');
INSERT INTO book(chapter,verse,content) VALUES(1,4,'<i>不要用哀伤的诗句对我说，</i>');
INSERT INTO book(chapter,verse,content) VALUES(1,5,'<i>人生不过是一场幻梦！</i>');
INSERT INTO book(chapter,verse,content) VALUES(1,6,'<i>昏睡的灵魂等于是死的，</i>');
INSERT INTO book(chapter,verse,content) VALUES(1,7,'<i>事物的真相与外表不同。</i>');
INSERT INTO book(chapter,verse,content) VALUES(1,8,'<i>生命是实在的，生命是真切的，</i>');
INSERT INTO book(chapter,verse,content) VALUES(1,9,'<i>坟墓并不是它的归宿！</i>');
INSERT INTO book(chapter,verse,content) VALUES(1,10,'<i>“你本是尘土，仍要归于尘土”，</i>');
INSERT INTO book(chapter,verse,content) VALUES(1,11,'<i>这话所说的并不是灵魂。</i>');
INSERT INTO book(chapter,verse,content) VALUES(1,12,'的确，那归于尘土的并不是灵魂。主耶稣在《马可福音》八章36节说：“人就是赚得全世界，却赔上自己的生命，有什么益处呢？”在耶稣基督的眼里，人的灵魂比世界上所有的东西都更加珍贵。');
INSERT INTO toc(title) VALUES('第二章 几个基本问题');
INSERT INTO book(chapter,verse,content) VALUES(2,1,'现在，就让我和你讨论几个人生的基本问题吧。这些问题和你最宝贵的灵魂有关。例如：');
INSERT INTO book(chapter,verse,content) VALUES(2,2,'<i>神真的存在吗？</i>');
INSERT INTO book(chapter,verse,content) VALUES(2,3,'<i>《圣经》记载的是真实的吗？</i>');
INSERT INTO book(chapter,verse,content) VALUES(2,4,'<i>人真的必须对神有所交代吗？</i>');
INSERT INTO book(chapter,verse,content) VALUES(2,5,'<i>神真的会饶恕人吗？</i>');
INSERT INTO book(chapter,verse,content) VALUES(2,6,'你如果认真思考自己的未来，这些就是最令你感到困扰的问题了。我怎样知道有神呢？');
INSERT INTO book(chapter,verse,content) VALUES(2,7,'我本能地相信神是存在的。我曾经尝试用理性设想出各种理由，来说服自己世上根本就没有神。无论我心中多么希望没有神的存在，但是总有一个“微小的声音”一次又一次地告诉我：“有神”。你在生活中宁静、清醒的片刻，不也曾听到这声音吗？我发现周围的人也在寻找');
INSERT INTO book(chapter,verse,content) VALUES(2,8,'神，他们尝试用“宗教”的信念去回应心中那微小声音的呼唤。');
INSERT INTO book(chapter,verse,content) VALUES(2,9,'的确，有些人并不相信神的存在。不过，对我来说，不相信有神，比相信有神，来得更加困难。');
INSERT INTO book(chapter,verse,content) VALUES(2,10,'试想想，那没有生命的物质是否可能自己产生智能，接着智能又自己产生良知呢？再想想，大自然中和谐有序的宇宙万物，难道是在杂乱混沌的虚无中偶然发生的吗？许多人竟然轻易地接受了这样的理论作为他们的信仰。');
INSERT INTO toc(title) VALUES('第三章 证明有神');
INSERT INTO book(chapter,verse,content) VALUES(3,1,'纽约科学学会 (New York Scientific Society) 的会长曾经提出8个理由，来说明为什么他相信有神。他这样来解释第一个理由。首先，你准备10枚相同的钱币，在每一枚钱币上分别写上一个号码，从1号写到10号；然后把它们放进口袋里。现在，从口袋中取出一枚钱币，你拿出1号钱币的几率是十分之一。然后把钱币放回去，再拿一枚出来——如果刚好是2号钱币，其总几率可不再是十分之一了，而是百分之一。如果想要按顺序从1号拿到10号，那总几率竟然是百亿(10,000,000,000)分之一。这真是一个叫人难以置信的天文数字啊！');
INSERT INTO book(chapter,verse,content) VALUES(3,2,'这就是为什么美国统计学家，乔治盖洛普(George Gallup) 说：“我能用统计学来证明有神。就以人的身体作为例子吧！如果说人体一切的功能都是出于偶然，其可能性，在统计学上是荒谬之论。”');
INSERT INTO book(chapter,verse,content) VALUES(3,3,'一个认真思考的人，应该不会把他永恒的未来，建立在“统计学的谬论”上吧？因此《圣经》在《诗篇》十四篇1节告诉我们：“愚顽的人心里说：没有上帝。”');
INSERT INTO book(chapter,verse,content) VALUES(3,4,'人或许会利用电脑和复杂的统计学来尝试证明有神。这其实是没有必要的。人只要稍做谦卑的反省，就会承认有一位创造的主宰，也就会同意诗人在《诗篇》一三九篇所说的：“耶和华啊，你已鉴察我，认识我…我往哪里去躲避你的灵？我往哪里逃，躲避你的面？”');
INSERT INTO toc(title) VALUES('第四章 第一个起因');
INSERT INTO book(chapter,verse,content) VALUES(4,1,'假设，我们站在机场一同观看一架巨型飞机从空中降落。我对你说：“许多人以为飞机是经过工程师精心设计制造而成的，不过我却认为这架飞机的由来根本不需要人类的智慧。起初，那些金属不知怎么的就从地底钻了出来，自己形成了一片片的金属板。然后这些金属板慢慢地就连接了起来，最后形成机身、机翼和机尾。又经过一段很长的时间，引擎也自己慢慢形成了。而后来有一天，有人就发现了这架构造完整、随时可以起飞的飞机。”');
INSERT INTO book(chapter,verse,content) VALUES(4,2,'你听了我的这些无稽之谈，肯定把我当成疯子。理由很简单，因为你知道，每一个设计的背后都必定有一位设计师。你已经看过人用智慧设计的各类产品，所以你能肯定地说，这架飞机也是靠着人的智慧和技能而制造出来的。');
INSERT INTO book(chapter,verse,content) VALUES(4,3,'许多善于思考的人相信上帝是超越宇宙的：祂在大自然中彰显祂自己，大自然的规律表露了祂的大能和智慧，而祂自己却超越宇宙。然而，还是有些受过高深教育的专业人士认为整个宇宙是偶然形成的，绝对没有更高的智慧在其中工作。他们也声称神不存在，一切都是出于自然。');
INSERT INTO book(chapter,verse,content) VALUES(4,4,'无神论者所提出的无非是一些人所不能解答的谜团：按照他们的理论，可以有设计却不需要有设计师、有受造物却不需要有创造者、有后果却没有前因。');
INSERT INTO toc(title) VALUES('第五章 看见才信！');
INSERT INTO book(chapter,verse,content) VALUES(5,1,'虽然人类发现了有关电的各种定律，但是，就连最出色的科学家也无法给电下一个真正的定义。那我们为什么还相信电的存在呢？因为我们在家中、在工业区里、在街道上，都已经看到电所发挥的各种功能。同样的，虽然我不知道神的来源，但我仍可以相信神的存在，因为祂的作为在我的周围处处可见。');
INSERT INTO book(chapter,verse,content) VALUES(5,2,'将美国第一颗航天卫星送入太空轨道的美国太空总署 (NASA) 署长——被称为导弹之父的布');
INSERT INTO book(chapter,verse,content) VALUES(5,3,'劳恩 (W.V.Braun) 博士说：');
INSERT INTO book(chapter,verse,content) VALUES(5,4,'“在这个新世代，随着科技的快速发展，有很多人觉得宗教信仰似乎已经过时或太古老了。他们认为通过科学我们已经可以‘理解’许多事物了，因此我们怎能满足于单单的‘相信’呢？对于这个争论，有个简单的答案：我们今天所面对的大自然界的奥秘，远远超过了科学');
INSERT INTO book(chapter,verse,content) VALUES(5,5,'启蒙时期。每每揭开一个奥秘，找到一个新的答案的同时，科学的探索往往又会发现至少三个新的问题。这告诉了我们什么呢？地球和宇宙中一切的事物这样井然有序、设计完美，其背后必定有一位创造者、一位设计师。如此有秩序、完美、精确平衡且宏伟的创造，只能出于上帝的意念。”');
INSERT INTO book(chapter,verse,content) VALUES(5,6,'已故的著名生物学家康克林 (Edwin Conklin)教授十分贴切地说：“如果说生命的起源是偶然发生的，其概率就好比说：一家印刷厂爆炸却产生出整本的钱伯斯 (Chamber’s) 英文字典来。”');
INSERT INTO toc(title) VALUES('第六章 神的启示');
INSERT INTO book(chapter,verse,content) VALUES(6,1,'不论人是否相信，神的存在终究是个事实。许多人不相信神的存在，并不是因为他们在理智上不能接受，而是因为相信有神将迫使他们思考自己应当如何向这位神作出交代。他们不愿意这么做，宁可选择相信“无神论”或“不可知论”，以为那是个方便的出路，好让自己不需要去面对这严峻的事实。可见，一般人的情况并非是“我不能信”，而是 “我不愿意信”。');
INSERT INTO book(chapter,verse,content) VALUES(6,2,'有两个方法可以让我们认识神和明白神的旨意。首先，你可以用理性的方法。一名出色的侦探通过观察我的所作所为，就能知道关于我的许多事情，包括我的技能、习惯和个性。同样的，你只要细心观察 神所创造的宇宙万物，就能从中认识到关于 神的某些特性。');
INSERT INTO book(chapter,verse,content) VALUES(6,3,'但是，这名侦探如果只单单观察我的所作所为，他永远不可能会因此而认识我。他或许知道关');
INSERT INTO book(chapter,verse,content) VALUES(6,4,'于我的某些事情，但我若要他真正的认识我，我就必须主动地向他表明我自己，和他沟通，告诉他我在想什么、我有什么感受和我要做些什么。我们可以通过交谈、书信或其他方式来达到这个目的。只有这样，他才有可能认识我。同样的，如果 神要我们认识祂，明白祂的思想、意念和旨意，祂就必须主动地将祂自己向我们启示，让我们可以在某个程度上认识祂。');
INSERT INTO toc(title) VALUES('第七章 书中之书');
INSERT INTO book(chapter,verse,content) VALUES(7,1,'在世界上所有的书籍当中，只有一本书宣称是由 神所直接启示的，这本书就是《圣经》。它告诉了我们有关 神自己的本性和祂对我们的旨意。《圣经》的确是如此的重要，实在值得我们详细考查。英国哲学家培根 (Francis Bacon)说：“先不要接受或拒绝，只要衡量和思考。”就让我们以这样的态度来探讨这本书奇特的宣称吧！');
INSERT INTO book(chapter,verse,content) VALUES(7,2,'在还没有阅读《圣经》以先就对它作出评价——这对我们自己、对《圣经》都是不公平的。法官还未完成审讯，不可以对案件下判决，我们对《圣经》的审评也理当如此。我们应当像法官一样，从双方证人所提供的证据，去衡量思考所发生过的事件，以便寻求其中深层的蕴涵，而不只满足于表面的意义。《圣经》既已发出如此重要的宣称，必定值得我们花时间去研读。《圣经》是由66本书卷组合而成的，写');
INSERT INTO book(chapter,verse,content) VALUES(7,3,'作时间跨越1600多年，写作地点纵横亚洲的巴比伦至欧洲的罗马，由至少40位不同的作者写成。《圣经》是这样写成的，我们或许可以预料，其中的内容必然会互相矛盾。奇妙的是，《圣经》的每一位作者所写的内容竟然前后完全一致，而且互相辅助。');
INSERT INTO toc(title) VALUES('第八章 神的标准');
INSERT INTO book(chapter,verse,content) VALUES(8,1,'接受《圣经》之后，我将面对一个严峻的考验:因为《圣经》所立下的道德标准是我达不到的。《圣经》说，凡无法达到这标准的人就是犯了罪。圣经要求说：“你要尽心、尽性、尽意爱主你的 神。这是诫命中的第一，且是最大的。”（《马太福音》二十二章37到38节）');
INSERT INTO book(chapter,verse,content) VALUES(8,2,'当你用这个标准来衡量自己时，你是否能够说，你这一生都已经完全做到了呢？你是否凡事都以 神居首位呢？要知道， 神监察我们每一个心思和意念。没有人敢说自己可以完完全全地做到。每颗诚实的心都会回应《罗马书》三章10节和三章23节所说的：“没有义人，连一个也没有…因为世人都犯了罪，亏缺了 神的荣耀。”世上所有的人都无法达到 神所要求的标准。');
INSERT INTO book(chapter,verse,content) VALUES(8,3,'一个年轻人曾经问我：“神所定下的圣洁标准这么高，明知我们是无法达到，却以此来审判世人，你认为这对我们公平吗？”我的回答是：“ 神并没有随随便便定下圣洁的标准。祂并不像一名长官那样可以随意地为身边护卫的身高定下标准。如果有人比标准矮了一寸，没有达到长官的要求，即使他拥有其他方面的资历，也会失去当护卫的资格。”');
INSERT INTO book(chapter,verse,content) VALUES(8,4,'其实， 神并没有定下任何标准：祂自己就是标准。 神是绝对圣洁的。因此，当祂和人交往时，也会保持绝对的圣洁。所以，有罪的人无法与圣洁的 神有交往，人离了神，自然而然地就会陷入罪恶的捆绑，无法自拔。');
INSERT INTO toc(title) VALUES('第九章 世人都犯了罪');
INSERT INTO book(chapter,verse,content) VALUES(9,1,'我的良知和经验都促使我承认，自己实在无法达到 神绝对圣洁的标准，因此，我在祂眼里是个污秽的罪人。');
INSERT INTO book(chapter,verse,content) VALUES(9,2,'当我知道自己有罪时， 神定罪的宣告就临到了我。正如《以西结书》十八章4节所说：“犯罪的他必死亡。”');
INSERT INTO book(chapter,verse,content) VALUES(9,3,'你可能会抗议说，犯了罪怎么就会死呢？让我打个比方来解释：英国的法律规定所有的车辆都必须靠左边驾驶，而美国的法律则规定车辆必须靠右边驾驶。有一天，我在英国伦敦因为开车靠右边驾驶，而被控上法庭，我对法官说：“这真是太荒谬了，在美国，我们可以靠右边驾驶汽车。”');
INSERT INTO book(chapter,verse,content) VALUES(9,4,'法官回答说：“你现在在英国，而不是在美国，所以我不用美国的法律，而是用英国的法律来审判你。”');
INSERT INTO book(chapter,verse,content) VALUES(9,5,'同样的，若按照 神的标准，我是有罪的 ，因为审判我的，是独一真神的律法。我已经犯罪，没有一丝盼望。我认识到，我的看法、或朋友的意见都不重要了。因为用来审判我的是 神的话语。更何况，在 神的律法下，每个人都犯了罪，因此向他人求助是无济于事的，因为他们和我一样，都在同一个律法下被定了死罪。');
INSERT INTO toc(title) VALUES('第十章 耶稣基督是 神的儿子吗？');
INSERT INTO book(chapter,verse,content) VALUES(10,1,'《圣经》告诉我，我是个罪人，《圣经》也告诉我，耶稣基督是 神的儿子。如果耶稣基督是神的儿子，那么祂肯定能够救赎我们，但问题是，耶稣基督真的是 神的儿子吗？');
INSERT INTO book(chapter,verse,content) VALUES(10,2,'这里有三个可能性：第一、祂真是 神的儿子；第二、他是个骗子；第三、他是个诚实的人，却处在幻觉之中。');
INSERT INTO book(chapter,verse,content) VALUES(10,3,'我们在《马太福音》二十二章46节里看到，一些非常聪明的人来刁难耶稣，想要抓住祂对话中的把柄，但耶稣的对答却反叫他们哑口无言，不敢多问。当我们理智地去审查耶稣当时充满智慧的言语时，就能清楚地看到，祂对自己的身份绝对肯定，并不是处在幻觉之中。难道祂是利用自己绝顶的聪明来蒙骗众人吗？');
INSERT INTO book(chapter,verse,content) VALUES(10,4,'你可曾听说过有哪个年轻人，因为和骗子、流氓同流合污，而变成一个高尚、纯洁又诚实的人呢？你肯定会说，不可能有这样的事。相反的，我认识一个年轻人，自从接受耶稣基督进入他的生命后，就离弃了过去非常腐败糜烂的生活，成为一个品格高尚的人。接受一个骗子进入一个人的生命，能够使这个坏人变成好人，这是我无法相信的。');
INSERT INTO book(chapter,verse,content) VALUES(10,5,'我曾经听一个人说，他现在之所以能够昂首挺胸做人，要归功于耶稣基督。因为有了耶稣，他才能以诚实清洁的心对待每一个人。');
INSERT INTO toc(title) VALUES('第十一章 在基督里都是新造的人');
INSERT INTO book(chapter,verse,content) VALUES(11,1,'整个文明世界的人都可以作证说，耶稣基督至少是个好人。若是好人，就一定是诚实不骗人的；若是诚实不骗人的，那祂对自己的宣称就必定是真的。祂自称是 神的儿子，降世为人，为了你和我的罪，舍下了祂那无罪的生命。');
INSERT INTO book(chapter,verse,content) VALUES(11,2,'前美国国会参议员哈特菲尔德 (Mark OHatfield) 说：“我曾经有31年，都是为自己而活。后来，我决定在剩余的生命中，只为耶稣基督而活。我也求 神赦免我过去以自我为中心的罪，让我为 神而活。自从跟随耶稣，我曾面对无数的挑战、体验了异乎寻常的经历、并且感受到无限的喜乐。为耶稣基督而活使我得到极大的满足，我的生命有了意义和方向，不再是满足自己，乃是事奉主耶稣基督。”');
INSERT INTO book(chapter,verse,content) VALUES(11,3,'前奥林匹克运动会田径明星理查兹 (Robert ERichards) 则说：“我参加赛跑的唯一目的，是');
INSERT INTO book(chapter,verse,content) VALUES(11,4,'要向全世界的年轻人做见证，让他们知道耶稣基督能够拯救我们脱离罪恶。基督徒也可以在良好的、具有创意的事业上有出色的表现。年轻人应当知道， 神已经藉着耶稣基督在加略山的死，彰显了祂的大能。”');
INSERT INTO toc(title) VALUES('第十二章 真诚是不足够的');
INSERT INTO book(chapter,verse,content) VALUES(12,1,'我并不要求你即刻就要接受耶稣，因为你也许会抗议说：“《圣经》看起来似乎是真理，但其他的观点也可能是对的。为什么不公平合理地审查其他的观点呢？”');
INSERT INTO book(chapter,verse,content) VALUES(12,2,'当我告诉一个朋友我的信仰时，他说：“你是对的，尽管我的看法和你的不同，但我也是对的。对我来说，一个人相信什么并不重要，最重要的是他忠于自己所信的。”');
INSERT INTO book(chapter,verse,content) VALUES(12,3,'让我们来查验这样的说法吧。在一个晴朗的星期天早晨，我的邻居对他的妻子和家人说：“让我们开车去郊外野餐吧。”当他开车北上，来到一个铁路道口时，他因为真诚地相信星期天早晨不会有火车经过，就把车直接开了过去，结果酿成大祸：他当场丧命，他儿子的手臂骨折，小女儿也需要包敷三个月的石膏。你说，他的真诚能救得了他吗？');
INSERT INTO book(chapter,verse,content) VALUES(12,4,'我认识一名护士，当她值夜班，给病人服药时，她真诚地相信所给的药物是正确的。但是她错了，她的病人在服用药物20分钟后就逝世了，无论医护人员如何努力抢救都无法挽回那个病人的性命。');
INSERT INTO book(chapter,verse,content) VALUES(12,5,'我们固然需要真诚，但我们所真诚相信的，应该是真理，而不是错误，否则，真诚地相信错误将会蒙蔽我们的心，使我们遭害。');
INSERT INTO toc(title) VALUES('第十三章 条条大路都通到天堂吗？');
INSERT INTO book(chapter,verse,content) VALUES(13,1,'《圣经》所宣告的很明确，让人不可置疑。在《约翰福音》十四章 6 节，耶稣说：“我就是道路、真理、生命；若不借着我，没有人能到父那里去。” （这里的父指的是创造宇宙的真神、天上的父。） 《使徒行传》四章 12 节说：“除祂（就是耶稣）以外，别无拯救；因为在天');
INSERT INTO book(chapter,verse,content) VALUES(13,2,'下人间，没有赐下别的名，我们可以靠着得救。” 耶稣基督已经宣告“别无拯救”，你若');
INSERT INTO book(chapter,verse,content) VALUES(13,3,'能使用另外一条道路通往天堂，就可以永远证明祂所说的是假的。可是，耶稣已经给了我们充足的证据，表明祂自己就是上帝的儿子。上帝既然指定要我们单单靠着耶稣基督回到祂那里去，我们却要寻找其他的途径，且自以为殊途同归，这不是很愚蠢的事吗？');
INSERT INTO book(chapter,verse,content) VALUES(13,4,'我们想要寻找另一条路的真正的原因是因为十字架的道路是卑微的，而我们的心却是骄傲的。但请不要忘记，十字架的道路对耶稣基督来说，');
INSERT INTO book(chapter,verse,content) VALUES(13,5,'也是卑微的，正如《腓利比书》二章5到8节所说：');
INSERT INTO book(chapter,verse,content) VALUES(13,6,'<i>“你们当以基督耶稣的心为心；祂本来</i>');
INSERT INTO book(chapter,verse,content) VALUES(13,7,'<i>有 神的形象，却不坚持自己与 神平</i>');
INSERT INTO book(chapter,verse,content) VALUES(13,8,'<i>等的地位，反而倒空自己，取了奴仆的</i>');
INSERT INTO book(chapter,verse,content) VALUES(13,9,'<i>形象，成为人的样式；既然有人的样子，</i>');
INSERT INTO book(chapter,verse,content) VALUES(13,10,'<i>就自甘卑微，顺服至死，而且死在十字</i>');
INSERT INTO book(chapter,verse,content) VALUES(13,11,'<i>架上。”</i>');
INSERT INTO book(chapter,verse,content) VALUES(13,12,'《圣经》多次肯定地说耶稣就是真神。如果我们接受这个事实，就没有必要再争论哪一条道路是通向天堂的了。耶稣在《约翰福音》十四章9到10节说：“人看见了我，就是看见了父…我在父里面，父在我里面…。”');
INSERT INTO toc(title) VALUES('第十四章 有债当还');
INSERT INTO book(chapter,verse,content) VALUES(14,1,'有些人认为，一个人只要诚恳地洗心革面，重新做人，改掉过去的坏行为，以后多做好事，就可以弥补过去的不是。他们以为这样就可以得到上天堂的资格了。果真如此吗？');
INSERT INTO book(chapter,verse,content) VALUES(14,2,'让我打个比方。有一个经理，得知公司亏欠了制造商和其他商家5万块钱，就对会计师说：');
INSERT INTO book(chapter,verse,content) VALUES(14,3,'“写信告诉这些人，过去我们所拖欠的债务从此一笔勾销。我们要重新开一本账簿，并且承诺他们，今后我们公司将会遵守最高的商业道德标准，如期偿还以后所有的债务。”');
INSERT INTO book(chapter,verse,content) VALUES(14,4,'会计师一定会以为经理精神失常了，他更不会遵照经理的吩咐去做。可是，今天却有许多看似明白事理的人就好像那位经理，企图借这种方法来进入天堂。他们向神承诺，今后会履行自己对神的一切义务，却不愿意对付过去所犯下的罪。《传道书》三章15节告诉我们：“ 神');
INSERT INTO book(chapter,verse,content) VALUES(14,5,'再寻回已过的事。”即使我们能够靠着自己重新开始一个完美的生命（其实那是人根本做不到的），却依然不能改变一个事实——我们仍然是罪人。');
INSERT INTO book(chapter,verse,content) VALUES(14,6,'耶稣来，是为了偿还我们的罪债，这债不是祂欠下的，而是我们欠下却没有能力清还的。 神');
INSERT INTO book(chapter,verse,content) VALUES(14,7,'的话宣告：“犯罪的灵魂必定会死。”《罗马书》五章8节说：“唯有基督在我们还作罪人的时候为我们死， 神的爱就在此向我们显明了。”');
INSERT INTO toc(title) VALUES('第十五章 耶稣将罪债还清');
INSERT INTO book(chapter,verse,content) VALUES(15,1,'每一笔债务都必须还清，每一个义务都必须完成，这是公义的 神所要求的。一个人如果犯了');
INSERT INTO book(chapter,verse,content) VALUES(15,2,'杀人的罪，他也许可以暂时掩饰自己的罪行，在犯罪后做个模范公民。可是，一旦他被发现曾经杀过人，就要按着人的律法被判死刑。即使他在之后十年都没有杀人，但按照法律他依然是个杀人犯。');
INSERT INTO book(chapter,verse,content) VALUES(15,3,'也许我们以为，用一个目前完美的人生可以掩饰过去在思想、言语或行为上所犯的各种罪。但是， 神能够洞悉过去、现在和未来的一切，在祂的眼中，我们依旧是个罪人。按照 神圣洁的标准，世人都犯了罪，我们必须在 神面前交账，按 神的公义受审判。');
INSERT INTO book(chapter,verse,content) VALUES(15,4,'那谁能替我们还清这些罪的账目呢？《圣经》告诉我们，唯有耶稣基督能替我们还清这笔罪债。《罗马书》五章10节说：我们“借着 神儿');
INSERT INTO book(chapter,verse,content) VALUES(15,5,'子的死，得与 神和好”。主耶稣基督牺牲自己的生命，代替我们受死，让我们从罪债中得到释放。我们得罪了 神，然而祂自己却为我们偿');
INSERT INTO book(chapter,verse,content) VALUES(15,6,'还了所有的罪债。耶稣基督在十字架上完成了救赎的工作，虽然死了， 神却叫祂复活。这表');
INSERT INTO book(chapter,verse,content) VALUES(15,7,'明祂对耶稣的救赎之工感到满意，也就是我们的罪债被还清的证据了。被钉十字架受死的基督，已经复活，成了我们永远活着的救主。祂受死，为要救我们脱离罪的刑罚。如今，祂仍活着，为要使我们脱离罪的权势。');
INSERT INTO book(chapter,verse,content) VALUES(15,8,'有一首诗歌这样写道：');
INSERT INTO book(chapter,verse,content) VALUES(15,9,'<i>我听救主说道：“你力量实微小！</i>');
INSERT INTO book(chapter,verse,content) VALUES(15,10,'<i>应当警醒祈祷，因我为你中保。”</i>');
INSERT INTO book(chapter,verse,content) VALUES(15,11,'<i>主替我舍身，罪债全还清，</i>');
INSERT INTO book(chapter,verse,content) VALUES(15,12,'<i>无数罪孽污秽心，主洗得比雪更白。 - 埃尔维纳霍尔 (Elvina M Hall)</i>');
INSERT INTO toc(title) VALUES('第十六章 完美的牺牲');
INSERT INTO book(chapter,verse,content) VALUES(16,1,'也许你会问，耶稣基督为什么需要受死呢？祂非要受死才能拯救我们吗？人既然违反了 神的');
INSERT INTO book(chapter,verse,content) VALUES(16,2,'律法，所该受的刑罚就是死。耶稣基督如果不全然担负起这刑罚，又怎能按着 神的公义来拯');
INSERT INTO book(chapter,verse,content) VALUES(16,3,'救我们呢？如果耶稣没有完全还清我们的罪债，我们不是仍要面对 神的审判吗？很显然的，因');
INSERT INTO book(chapter,verse,content) VALUES(16,4,'为耶稣已经为我们死了，我们所违反的律法就不能再定我们的罪了。');
INSERT INTO book(chapter,verse,content) VALUES(16,5,'《圣经》在《罗马书》八章1节说：“如今，那些在基督耶稣里的，就不定罪了。”');
INSERT INTO book(chapter,verse,content) VALUES(16,6,'有一次，法庭將一宗案件展延到隔天继续审讯。为了不让陪审员受到外界的影响，他们按照常例被隔离起来。第二天早上，法官对陪审员说：“诸位，案件被撤销了。犯人已经被移交到更高的法庭去了。”原來，这名嫌犯前一个晚上');
INSERT INTO book(chapter,verse,content) VALUES(16,7,'在牢狱中死了，已经没有必要继续审理案件，因为法律无法审判一个已死的人。');
INSERT INTO book(chapter,verse,content) VALUES(16,8,'一个人如果谋杀了另一个人，他一定会被判死刑；即使他杀了六个人，也还是要面对同样的刑罚。因为死是人所能面对的最严厉的刑罚。不论一个人犯了多大的罪，法律最终能够执行的刑罚就是夺取那人的生命。');
INSERT INTO toc(title) VALUES('第十七章 但不全都得救');
INSERT INTO book(chapter,verse,content) VALUES(17,1,'耶稣基督的牺牲是那么的伟大完美，因此有人会认为说，祂既然是为世人而死的，那么我们所有的人必定都能得救。但 神并不是这么说的。');
INSERT INTO book(chapter,verse,content) VALUES(17,2,'神说明救恩是为全人类所预备的，可是并非每一个人都会得救。');
INSERT INTO book(chapter,verse,content) VALUES(17,3,'打个比方说，在一个极其寒冷的冬天，一个大城市中有很多贫困的人急需救济，于是市政府为他们供应了免费的食物。如果你在路上碰到一个可怜的人，他说自己已经饿慌了，你自然会问他：“朋友，城里到处都贴着告示说，市政府已经预备好足够的食物免费提供给所有需要救济的人，难道你不相信吗？”');
INSERT INTO book(chapter,verse,content) VALUES(17,4,'他回答说：“是的，我相信应该有此事吧，但我还是很饿啊。”');
INSERT INTO book(chapter,verse,content) VALUES(17,5,'你就会告诉他说：“食物已经预备好了，你若不亲自领取享用，就只好继续挨饿了。”');
INSERT INTO book(chapter,verse,content) VALUES(17,6,'神借着基督耶稣的死为世人预备了救恩。但是只有当一个人亲自接受了耶稣——相信耶稣代他而死，才能得救。我必须接受基督耶稣成为我个人的救主，否则祂的死与我无益。正如一个人即使身在泉水旁，如果他不肯自己喝下这股赐生命的泉水，最终仍会渴死。');
INSERT INTO book(chapter,verse,content) VALUES(17,7,'主的救恩是赐给每一个人的：凡饥渴的人都可以来领取！耶稣说：“凡劳苦担重担的人，可以到我这里来。”（《马太福音》十一章 28节）');
INSERT INTO toc(title) VALUES('第十八章 除罪的奥秘');
INSERT INTO book(chapter,verse,content) VALUES(18,1,'还有人会问：“神已赐下救恩给所有信靠耶稣基督的人，可是耶稣一个人的生命，怎么能代替那么多人的生命呢？”');
INSERT INTO book(chapter,verse,content) VALUES(18,2,'这似乎是一个合理的、用数学公式就足以证明的问题。岂不知耶稣基督就是道成肉身的真神。因此，祂所舍下的是无限的生命，可以满足世上一切有限的生命的需要。');
INSERT INTO book(chapter,verse,content) VALUES(18,3,'现在，让我们做一个实验。请你拿出纸和笔来，写下你能够想像到的最大的数字，可以是一百万、一千万，甚至更大；再把这些数字加起来，然后乘以百或千，甚至百万。即使你填满整张纸，最终你写下的仍然是一个有限的、一个有始又有终的数字。');
INSERT INTO book(chapter,verse,content) VALUES(18,4,'可见，世上从来没有人能把有限的东西加在一起，使之变成无限的。相反的，耶稣基督所舍');
INSERT INTO book(chapter,verse,content) VALUES(18,5,'下的生命却是无限的，足以拯救所有相信祂的人。');
INSERT INTO book(chapter,verse,content) VALUES(18,6,'你可能又会提出另一个问题：基督耶稣在两千年前已经死了，祂怎能为我今天所犯的罪受苦呢？');
INSERT INTO book(chapter,verse,content) VALUES(18,7,'这好像是个棘手的问题，但你若仔细想一想，就不难看到问题的答案了。 神是无所不知的，是永恒的；祂在《出埃及记》三章14节里宣称');
INSERT INTO book(chapter,verse,content) VALUES(18,8,'自己是“自有永有的”。耶稣基督在《约翰福音》八章58节里也说：“还没有亚伯拉罕就有了我。”换句话说，全知永恒的 神是没有过去');
INSERT INTO toc(title) VALUES('第十九章 是人，并非木偶');
INSERT INTO book(chapter,verse,content) VALUES(19,1,'你也许会问，既然神创造了人，为什么神没有使人不能违背祂的旨意呢？那么人就不会犯罪了呀！这就好比问 神：为什么不把一条直线画');
INSERT INTO book(chapter,verse,content) VALUES(19,2,'成弯的，或者把一个方形画成圆的，或者造一件完全是黑色，又同时完全是白色的物体呢？人虽是受造的，却具有自由选择的能力。关键的问题是： 神是否要创造一个既有自由意志，同时不能做出自由选择的人?');
INSERT INTO book(chapter,verse,content) VALUES(19,3,'我如果有催眠的本事，就可以让我的两个儿子进入催眠的状态，夺取他们做自由选择的能力。这样，我可以任意地吩咐他们：“坐着不许动”、“起来，吃饭”、“不准吃”、“和我说晚安”、“亲亲我”。这样，他们就会用毫无感情的双手抱着我，用他们麻木的嘴唇亲吻我。无论我要他们做什么，他们都会完全服从，可是这会令我感到满意吗？绝对不会！');
INSERT INTO book(chapter,verse,content) VALUES(19,4,'我对我儿子的要求，是让他们用自由的意志选择去甘心服从我的指示，听从我的教导，他们虽然可以抗拒我，但却选择乐意顺服我。他们也知道我的指示乃是出于爱，对他们是有益的。');
INSERT INTO book(chapter,verse,content) VALUES(19,5,'我想， 神把意志放在你我的心中，对我们的要求也是如此。 神不要我们像木偶被铁线牵来拉');
INSERT INTO book(chapter,verse,content) VALUES(19,6,'去，也不要我们像机器人一般机械化地，或如行星绕着恒星一成不变的旋转一样，绝对地服从祂的指示。最能令 神满意的是我们对祂出于');
INSERT INTO toc(title) VALUES('第二十章 神所爱的对象');
INSERT INTO book(chapter,verse,content) VALUES(20,1,'人类的确是 神最伟大的创造，是万物之灵，远远超越一切的动物。人与动物之间根本没有进化论所谓的“失落的环节”。相反的，人与动物之间却有一道巨大而不可跨越的鸿沟。因着 神赐给人的特权，人可以对 神说“不”，也可以对 神说“是”。现在，让我问你一个切身的问题：“当你听了1这福音信息后，你会向 神说‘ 不’ ，或说‘ 是’ 呢？”');
INSERT INTO book(chapter,verse,content) VALUES(20,2,'和浩瀚无穷的宇宙相比，我们的地球是多么的渺小。神为何要顾念我们呢？');
INSERT INTO book(chapter,verse,content) VALUES(20,3,'请看地球所处的太阳系吧！它是如此的浩瀚，海王星和太阳之间的距离，比地球和太阳的距离多了 30 倍。海王星环绕太阳运行一周，需要地球的 164 年。除了太阳系，太空中还有无数');
INSERT INTO book(chapter,verse,content) VALUES(20,4,'的恒星系统，就像太阳系一样，由行星环绕着');
INSERT INTO book(chapter,verse,content) VALUES(20,5,'恒星运行。相比之下，地球在 神的眼里算得了什么？人岂不是更微不足道吗？');
INSERT INTO book(chapter,verse,content) VALUES(20,6,'曾经有一位天文学家，在他年轻时，因为用望远镜看到太空的浩大，竟然因此而丢弃了小时候母亲教导他的信仰。他想：“人比一粒沙子还渺小，神为什么还要顾念他呢？”');
INSERT INTO book(chapter,verse,content) VALUES(20,7,'但是他的求知欲叫他闲不下来。他想：“我只能在夜里研究天空，那么白天我要做些什么呢？不如拿个显微镜来看看。”结果，他这么一看，一个新的世界展现在他眼前，显微镜中的世界竟然和太空世界一样奇妙。渐渐地，他又重新拾回对 神的信心。是的，他看到，就是一小滴污水都充满无数的微生物， 神连这么微小的生');
INSERT INTO book(chapter,verse,content) VALUES(20,8,'命都照料到，祂也必定顾念祂最伟大的创造物——人。这位天文学家在知识的探索中排除了偏见，找到了平衡，使他回归 神。他发现《约翰福音》三章 16 节说的“ 神爱世人”，是多');
INSERT INTO toc(title) VALUES('第二十一章 信心坚固的基础');
INSERT INTO book(chapter,verse,content) VALUES(21,1,'信心是否合逻辑？是合逻辑的。有人错误地以为信心和理智是互相抵触的，其实信心和理智是相辅而行的，而且当理智停滞不前的时候，信心却能够继续向前迈进。理智在一个相当的程度上是有赖于信心的，因为没有知识就不能够运用理智，而知识本身又往往以信赖他人的见证为基础。比如说，有报道说服用大量的“士的宁” (Strychnine) 这种药物会使人中毒致命，虽然我从来没有亲眼看过任何一个实验证实这个报道，我仍会相信别人报道他们所考证的，因此我不会随便大量服用这种药物。');
INSERT INTO book(chapter,verse,content) VALUES(21,2,'如果你仔细查验，就不难发现，你所知道的很多事情都是从别人那里听来的，你并没有自己去考证就相信接受了。你既然在许多事情上可以接纳人的见证，那为什么就不能接受千千万万个基督徒对于他们信仰的见证呢？他们不但');
INSERT INTO book(chapter,verse,content) VALUES(21,3,'考证了 神的话语，并且用生命的实践来证实那的确是真理。');
INSERT INTO book(chapter,verse,content) VALUES(21,4,'人之所以不信，并不是因为没有看到神权能的彰显，而是因为内心的刚硬。你看看《圣经》中《出埃及记》记载的那位顽固的法老。虽然');
INSERT INTO book(chapter,verse,content) VALUES(21,5,'神为了拯救以色列百姓，借着摩西的手，施展了威严的作为，非但没有使法老的心屈服，反而使他不信的心更加刚硬。不过，更叫人惊讶和哀叹的是以色列百姓在旷野的不信与悖逆。即使 神分开红海、毁灭法老庞大军队的情景仍');
INSERT INTO book(chapter,verse,content) VALUES(21,6,'然历历在目，却还是无法阻止他们对上帝和摩西的背叛。');
INSERT INTO book(chapter,verse,content) VALUES(21,7,'我们的信心不是以人的假设或猜测为基础，而是根据永活的耶稣基督所说的话和所做的工。这位至高、掌管万有的 神，很快就要再次降临，');
INSERT INTO toc(title) VALUES('第二十二章 罪的工价乃是死');
INSERT INTO book(chapter,verse,content) VALUES(22,1,'为什么 神断定我们的罪是该死的呢？那是因为神是绝对圣洁的，祂不容许在祂面前有任何罪的存在。在一些原始文化中，土著酋长可以因为妻子的一个小小过错，就用棍子打死她。这并不会影响酋长在部族中的声望地位。但是，如果这种事情发生在文明的社会里，杀了人就得偿命。同样的一件事情发生在不同社会，会产生不同的后果：一个是杀人者没有受到审判，一个则是立刻得到该受的惩罚。之所以会产生这两种不同的后果，是因为社会文明程度的不同。同样是杀人罪，在原始社会中不被当作一回事，在文明社会中却是死罪。');
INSERT INTO book(chapter,verse,content) VALUES(22,2,'同样的，有些事对我们来说并不是罪，但在绝对圣洁的 神眼里却是罪，因为《约翰一书》一章 5 节说：“ 神就是光，在祂毫无黑暗。”');
INSERT INTO book(chapter,verse,content) VALUES(22,3,'你也许会问：如果我们拒绝让耶稣除去我们的罪，而神就因此不让我们进入天堂，这或许是出于祂的公义。不过，神这么做还算是有怜悯吗？答案是肯定的：这是出于 神的公义，也是出于祂的怜悯。让我来解释。');
INSERT INTO book(chapter,verse,content) VALUES(22,4,'如果我把一个穿著破烂的乞丐带去一个富丽堂皇的宴会厅，你认为我这么做是对他好吗？其实，在华丽的厅堂中，闪耀刺眼的灯光只会让他在众人面前抬不起头，与其让自己的污秽暴露无遗，倒不如逃回黑暗的巷子里，在那里他会觉得比较自在。同样的，一个人充满罪污，又拒绝被洗干净，如果 神把他带到圣洁光明的天堂，这算是出于慈爱和怜悯吗？');
INSERT INTO book(chapter,verse,content) VALUES(22,5,'试想，你和我都不愿意让朋友知道自己现在在想什么或曾经有过的一切思想和意念（也许这些朋友的道德标准不一定比自己的标准高）。那么，当我们站在绝对圣洁的 神面前，我们一');
INSERT INTO toc(title) VALUES('第二十三章 地狱没有出口');
INSERT INTO book(chapter,verse,content) VALUES(23,1,'那些拒绝将耶稣基督作为他们的救主，又坚持带着罪进入永恒的人，他们将如何面对末日的审判呢？《圣经》在《启示录》六章 16 节是这样形容这些人在审判时心中的感受——他们要');
INSERT INTO book(chapter,verse,content) VALUES(23,2,'向山和岩石呼喊说：“倒在我们身上吧！把我们藏起来，躲避坐在宝座上那位的面，…。”相反的，对于那些已经接受耶稣作他们的救主');
INSERT INTO book(chapter,verse,content) VALUES(23,3,'和生命的主宰的人，耶稣基督的同在却能让他们感受到天堂的喜乐。');
INSERT INTO book(chapter,verse,content) VALUES(23,4,'现在你终于看到，神会接纳所有人到天堂去的说法是多么的荒谬。天堂不仅是一个真实的地方，也是一种实际的状态。那些罪得赦免的人，有主耶稣基督同在，就是天堂；然而那些依然沉沦在罪中的人，站在绝对圣洁的耶稣容光面前，心里只有地狱般的懊悔。让我们理智的思考一下这个问题：如果你拒绝了主耶稣的爱，你不屑接受主耶稣为你所作出的牺牲，当你来到祂面前的时候，你真的会快乐吗？');
INSERT INTO book(chapter,verse,content) VALUES(23,5,'地狱是个无法回头、没有出口的地方。那些已经进去的，只能继续待下去。通往地狱的，是一条单行道。单行道的入口处竖立着告示牌警告说：“快逃出 神的愤怒，进入祂儿子的膀臂吧！接受 神儿子的人就有生命！”你何必灭亡呢？今天，就让这告示牌来唤醒你吧！');
INSERT INTO book(chapter,verse,content) VALUES(23,6,'只有拒绝 神儿子的人，才会下到地狱去。他们也只能责怪自己。约翰加尔文 (John Calvin) 说：“恶人在自己的心里播下地狱的种子。”恶人指的是谁呢？《启示录》二十一章 8 节告诉我们，他们就是“…那些胆怯的、不信的、可憎的、杀人的、淫乱的、行邪术的、拜偶像的和');
INSERT INTO toc(title) VALUES('第二十四章 基督，我们的代罪者');
INSERT INTO book(chapter,verse,content) VALUES(24,1,'我们已经谈过 神存在的例证，还有祂如何通过《圣经》的启示，向全人类所作的宣告。我们也指出了《罗马书》三章 23 节所说的：“世人都犯了罪，亏缺了 神的荣耀”。我们看到了');
INSERT INTO book(chapter,verse,content) VALUES(24,2,'神的儿子耶稣基督降世为罪人受死。我们也思考过反对 神救赎方法的人所提出的许多异议。现在，我们要来思想 神如何用祂的智慧，为罪');
INSERT INTO book(chapter,verse,content) VALUES(24,3,'人安排了奇妙的救赎。简单的说，耶稣基督代替我们受死，救赎的工作就完成了。这就是“代罪救赎”的道理。');
INSERT INTO book(chapter,verse,content) VALUES(24,4,'虽然 神因着祂的慈爱愿意赦免罪人，但祂的公义却不容许祂这么做。按照 神的公义，祂必定要审判罪人，但 神的爱却抑制了祂即时的刑罚。 神是完全的公义，但祂也是完全的慈爱， 神的');
INSERT INTO book(chapter,verse,content) VALUES(24,5,'这两种属性要如何并存，是哲学家无法解决的难题。但 神自己的解决方法，却表现出祂至高');
INSERT INTO book(chapter,verse,content) VALUES(24,6,'的智慧和无限的怜悯。 神的方法就是让祂的儿子代替世人受苦，以至受死。');
INSERT INTO book(chapter,verse,content) VALUES(24,7,'或许有人会反对说：“基督教以代罪作为救赎的基础，岂不是根本上的错误吗？”他们认为“代罪救赎”这个方法是站不住脚的。耶稣基督代替罪人受刑罚，就是让完全无罪的受刑，有罪的却被释放而获得自由，这正好与司法制度的原则互相抵触。因为法律是公正的，应当保护无罪的，而有罪的应该承担所有的刑罚。');
INSERT INTO book(chapter,verse,content) VALUES(24,8,'在埃及的第一个逾越节 (Passover)，每一户以色列家庭都因为羔羊的血而免去死亡。以撒 (Isaac) 的生命因为一头公羊的取代而得到救赎。');
INSERT INTO toc(title) VALUES('第二十五章 十字架是我们的荣耀');
INSERT INTO book(chapter,verse,content) VALUES(25,1,'我们看到， 神已经借着十字架彰显出完全的公义和无限的怜悯。 神并没有强迫一个无罪的人');
INSERT INTO book(chapter,verse,content) VALUES(25,2,'代替有罪的人承担刑罚。让我用一个故事来解释这一点：有两个年轻人曾经一起攻读法律，其中一个当上了法官，另一个却因为酗酒而断送了前程。有一回，这名酒徒因为犯法被控上法庭，恰巧被带到他的老同学面前受审。在场的律师知道法官处在两难之间，正猜想他要如何下判呢？审案的结果令他们十分惊讶。法官宣判他的老同学必须缴付法律上最高的罚款，然后自己却为他偿还了所有的罚款，并释放了他。 神为我们所做的就像这故事中的法官为他老同学所做的一样。');
INSERT INTO book(chapter,verse,content) VALUES(25,3,'神因着祂的公义 ，坐在审判的宝座上，对我们这些罪人作出了最严厉的判决，就是死刑。然后， 神又因着祂的怜悯，从宝座上走了下来，');
INSERT INTO book(chapter,verse,content) VALUES(25,4,'借着祂的独生爱子，亲自代替罪人，担当了全');
INSERT INTO book(chapter,verse,content) VALUES(25,5,'部的刑罚。《哥林多后书》五章 19 节告诉我们：“…上帝在基督里…”由此可见，上帝不仅是');
INSERT INTO book(chapter,verse,content) VALUES(25,6,'借着耶稣基督，而且在耶稣基督里“叫世人与自己和好。”');
INSERT INTO book(chapter,verse,content) VALUES(25,7,'保罗所传扬的那独一不变的信息就是：“耶稣基督，以及祂被钉十字架”。因为耶稣被钉十字架，灭亡的灵魂就得着永远的生命。今天，这灭亡的世界拒绝或曲解了十字架的信息。对他们来说，这信息是愚蠢的。对我们这些已经被救赎的人来说，这是 神的大能。世人被骄傲蒙蔽了双眼，因此藐视被钉的救主。');
INSERT INTO book(chapter,verse,content) VALUES(25,8,'英国伟大的圣诗作者以撒瓦兹 (Isaac Watts) 这样表达了十字架的信息：');
INSERT INTO toc(title) VALUES('第二十六章 最公平的邀请');
INSERT INTO book(chapter,verse,content) VALUES(26,1,'圣父、圣子和圣灵乃是三位一体的独一真神。我们所得罪的就是这位公义的 神。祂已经审判');
INSERT INTO book(chapter,verse,content) VALUES(26,2,'了我们，同时也替我们还清了罪债，按照祂自己绝对公义的标准，白白地赐给我们完全的赦罪之恩。因此，使徒保罗在《罗马书》一章 16和 17 节说：“我不以福音为耻，这福音本是 神的大能，要救一切相信的…因为 神的义，正');
INSERT INTO book(chapter,verse,content) VALUES(26,3,'在这福音上显明出来。”我同样可以说：我不以基督的福音为耻，因为 神赐给人的赦罪之恩，');
INSERT INTO book(chapter,verse,content) VALUES(26,4,'使人可以得称为义，是没有任何缺陷的。如果你愿意接受耶稣基督的赦罪之恩，就可以立刻在 神面前得称为义人了。');
INSERT INTO book(chapter,verse,content) VALUES(26,5,'你也许会问：“只要接受耶稣成为我个人的救主，就足以让我永远得救吗？”答案是肯定的。这方法听起来实在简单得令人难以置信。假设我欠了某人 500 块钱却无法偿还，而一个朋友');
INSERT INTO book(chapter,verse,content) VALUES(26,6,'替我还清了这笔债务，并且把收据交给了我，');
INSERT INTO book(chapter,verse,content) VALUES(26,7,'我就不必再为此事担心了。从此，我便可以坦然地面对债主，因为我手上拿着他亲笔签名的收据。同样的，耶稣基督代替我们受死，当祂说“成了”的时候，就表示 神的救赎工作已经完成， 神已经把祂“亲笔签名”的收据给了我们。 神叫耶稣基督死后第三天复活，就是祂悦纳基督救赎工作的确据。');
INSERT INTO toc(title) VALUES('第二十七章 成了！');
INSERT INTO book(chapter,verse,content) VALUES(27,1,'当我们接受耶稣基督为我们成就的公义时，我们就像穿上了一件完美无瑕的结婚礼服。你不能再加添一点自己的义，因为你的义在 神面前，只不过是一件肮脏、破烂的衣服。');
INSERT INTO book(chapter,verse,content) VALUES(27,2,'有一个木匠困扰地说：“这个道理我实在无法明白。” 木匠的朋友为了帮助他，终于想到了');
INSERT INTO book(chapter,verse,content) VALUES(27,3,'一个点子。他随手拿起一个木工刨，放在木匠身边刚做完的一张桌子上，好像就要动手去刨那光亮美丽的桌面。木匠赶紧喊道：“住手！难道你没看到那桌子已经完工了吗？你这样做，只会把桌子弄坏！”');
INSERT INTO book(chapter,verse,content) VALUES(27,4,'他的朋友回答说：“怎么？这不正和我所说的道理一样吗？耶稣基督为你舍命，已经完成了救赎的工作。如果你想再加添点什么，不但无济于事，反而会造成破坏。你必须做的只是接受祂已经完成的救赎之工——祂为你牺牲的生');
INSERT INTO book(chapter,verse,content) VALUES(27,5,'命，使你得着自由了。”木匠茅塞顿开，终于领悟了，并且接受了耶稣基督成为他的救主。');
INSERT INTO book(chapter,verse,content) VALUES(27,6,'《以弗所书》二章 8 到 9 节说：“你们得救是本乎恩，也因着信；这并不是出于自己，乃是');
INSERT INTO book(chapter,verse,content) VALUES(27,7,'神所赐的；也不是出于行为…。”救恩完全在于 神，也完全本乎恩。我们只需空手前来领受。');
INSERT INTO book(chapter,verse,content) VALUES(27,8,'救主耶稣已经完成的工作，我们不论做什么，也无法加添或改善。耶稣已经成就了祂完美的救赎之工，正如祂所说的：“成了！”');
INSERT INTO toc(title) VALUES('第二十八章 真正的分别');
INSERT INTO book(chapter,verse,content) VALUES(28,1,'也许有人会说：“我还有一个疑问，基督徒与非基督徒的分别在哪里呢？我认识一位很有修养的绅士，他不是基督徒。我也认识一位粗俗又没有修养的人，但他却是个基督徒，并且在生活上处处表现出他的信仰。难道说， 神接纳');
INSERT INTO book(chapter,verse,content) VALUES(28,2,'这个粗人，就因为他接受了耶稣基督为他的救主吗？”');
INSERT INTO book(chapter,verse,content) VALUES(28,3,'这个问题是由于概念上的混淆造成的。基督徒和非基督徒的分别，不是在于程度上的差距，而是在于本质上的不同。它们之间的分别，就好像一颗钻石和一个卷心菜的不同一样。虽然从表面看上去，钻石典雅而卷心菜平庸，但它们之间本质的不同在于——钻石是死的，而卷心菜是活的。非基督徒和基督徒在 神的眼中也');
INSERT INTO book(chapter,verse,content) VALUES(28,4,'是这样：这一个没有生命，那一个却是有生命的。');
INSERT INTO book(chapter,verse,content) VALUES(28,5,'在《约翰一书》五章 11 和 12 节里， 神这样宣告说：“这见证就是 神赐给我们永生，这永生也是在祂儿子里面。人有了 神的儿子就有生命；没有 神的儿子就没有生命。”因此，对每一个');
INSERT INTO book(chapter,verse,content) VALUES(28,6,'人来说，最重要和关键的问题，不是在于我是否是个文雅或粗俗的人，而是在于我在 神的眼中，是活的还是死的？我若接受 神的儿子，复');
INSERT INTO book(chapter,verse,content) VALUES(28,7,'活的耶稣基督，就得到祂从天上所赐的生命。这生命是 神所赐的，就是《圣经》所说的永生。相反的，我若不接受祂，在 神的眼中，我就是个没有生命的人。');
INSERT INTO book(chapter,verse,content) VALUES(28,8,'我们借着父母来到这个世界，开始了属肉体的生命。在这之后又是什么呢？耶稣告诉我们：“信的人有永生”。 神的圣灵赐给我们永生，使我们得以进入 神永恒的天国。你得到这新生');
INSERT INTO toc(title) VALUES('第二十九章 真心所属');
INSERT INTO book(chapter,verse,content) VALUES(29,1,'我当如何接受主耶稣基督成为我的救主呢？按《以弗所书》二章 1 节所说的，我已经知道自');
INSERT INTO book(chapter,verse,content) VALUES(29,2,'己是个“死在过犯罪恶之中”的人。我也相信耶稣基督已经为我舍命；并且，如果现在接受祂作为我的救主，我就能得到永恒的救恩。但是，如果只用冷漠的心和机械的态度去承认这些事实，它会给我带来永生吗？绝对不能！');
INSERT INTO book(chapter,verse,content) VALUES(29,3,'好比一个富翁，当他突然失去所有的财富后，为了挽回他的社会地位，就要把自己的女儿许配给另一个富翁。女儿起初因为鄙视那富翁，就断然拒绝了。可是父亲苦心劝告女儿说，这门亲事是帮助他们摆脱眼前困境的唯一方法。女儿出于无奈，终于和富翁举行了婚礼。虽然在法律上她成为了那个富翁的妻子，但她的心是否真的属于那富翁呢？肯定不是。这个故事告诉我们，一对男女若要结为夫妻，他们就必');
INSERT INTO book(chapter,verse,content) VALUES(29,4,'须从内心深处彼此接纳。这样才会有真诚且无法言喻的爱情。');
INSERT INTO book(chapter,verse,content) VALUES(29,5,'同样的，接受耶稣基督为救主也就是让祂进入我们心灵的深处。每个人心灵的深处都是隐秘而神圣的，是别人所不能视透的。 神的儿子耶');
INSERT INTO book(chapter,verse,content) VALUES(29,6,'稣基督向我们彰显了大爱，为的就是要得着我们的心。');
INSERT INTO book(chapter,verse,content) VALUES(29,7,'耶稣基督舍弃了天父的荣耀，来到了世上，为我的罪受死，并赐给了我永生。每当想到祂如此的爱我，怎能不叫我心中感动呢？我是否还要拒绝祂呢？');
INSERT INTO toc(title) VALUES('第三十章 奇妙的爱');
INSERT INTO book(chapter,verse,content) VALUES(30,1,'现在，我来到我的救主耶稣跟前。在祂为我被钉十字架之前，我看到祂在客西马尼园痛苦的祷告。我看到祂在本丢彼拉多 (Pontius Pilate)');
INSERT INTO book(chapter,verse,content) VALUES(30,2,'的审判大堂里，兵丁把祂拷打得遍体鳞伤，给祂戴上用荆棘做的冠冕，并嘲弄祂说：“你是先知，告诉我们打你的是谁！”在审判之后，兵丁把祂带到加略山，用钉子将祂的手和脚钉在十字架上，并将十字架竖立在两个盗贼中间。祂流出的血所要拯救的，不正是那些围绕着祂，嘲笑、辱骂祂的人吗？我却听到祂喊着说：“父啊，赦免他们，因为他们所作的，他们不晓得”。当我看到、听到这一切的时候，我才开始明白自我牺牲的爱的真正意义。');
INSERT INTO book(chapter,verse,content) VALUES(30,3,'但是，就算我们能够身历其境地体会基督耶稣在肉体上所受的痛苦，并为之泪流满面，却还是无法完全理解十字架的真正意义。《哥林多后书》五章 21 节说：“ 神使那无罪的替我们成');
INSERT INTO book(chapter,verse,content) VALUES(30,4,'为罪。”我恳求你和我一起，低下头，带着谦卑的心，一同来感受天父上帝和祂儿子耶稣基督，在灵性上所忍受的磨难。岂不知，这位憎恶罪恶，就如我们憎恶麻风病一样的至圣者，竟然代替我们，“成为了罪”。');
INSERT INTO book(chapter,verse,content) VALUES(30,5,'请你默想， 神的爱倾注在我们这些叛逆之人的身上。这是多么的奇妙。我想起了著名英国诗人以撒瓦兹 (Isaac Watts) 这样来描写十字架的爱：');
INSERT INTO book(chapter,verse,content) VALUES(30,6,'<i>試看其頭其足其手， 慈愛憂愁和血並流， 如此愛憂自古焉有? 荆棘反成荣耀冕旒。</i>');
INSERT INTO toc(title) VALUES('第三十一章 祂替我们成为罪');
INSERT INTO book(chapter,verse,content) VALUES(31,1,'一般来说，越高等的生物，对疼痛的感觉就越敏锐。同样的，一个人对道德的标准要求越高，因罪恶而感受到的痛苦就越深。');
INSERT INTO book(chapter,verse,content) VALUES(31,2,'有一个这样的故事： 一位受人尊敬并以自己的名誉为尊荣的父亲，他宁愿失去右手，也不愿做出任何不正当的事。可是令他痛心的是，他的儿子却误入歧途。有一天他的儿子因为醉酒与人起了争执，结果杀了人。从那以后父亲羞愧得再也无法抬起头来，他的灵魂也不断地受到折磨，最后郁郁而终。');
INSERT INTO book(chapter,verse,content) VALUES(31,3,'人的罪在自己的眼中，尚且叫他感到羞愧。更何况，在绝对圣洁的 神的眼中，人的罪该会是');
INSERT INTO book(chapter,verse,content) VALUES(31,4,'多么的令祂憎恶？我们现在明白，为何耶稣在客西马尼园强烈地表达对罪的憎恶，并痛苦地向 神哀求：“我父啊，倘若可行，求你叫这杯');
INSERT INTO book(chapter,verse,content) VALUES(31,5,'离开我；然而，不要照我的意思，只要照你的');
INSERT INTO book(chapter,verse,content) VALUES(31,6,'意思”（《马太福音》二十六章 39 节）。尽管耶稣如此痛苦地呼求，但“ 神爱世人，甚至将');
INSERT INTO book(chapter,verse,content) VALUES(31,7,'祂的独生子赐给他们”——“替我们成为罪”——“叫一切信祂的，不至灭亡，反得永生” （《约翰福音》三章 16 节，《哥林多后书》五章 21 节）。');
INSERT INTO book(chapter,verse,content) VALUES(31,8,'救赎的奥秘就在于：天父使祂唯一的独生子耶稣基督“替我们成为罪，好叫我们在祂里面成为 神的义。”所以你要仰望在十字架上为你担');
INSERT INTO toc(title) VALUES('第三十二章 接受主耶稣');
INSERT INTO book(chapter,verse,content) VALUES(32,1,'救恩的奥秘属于 神，我们无法完全理解，但这不妨碍我们从救主耶稣基督那里得着无限的好处。正如我们只管享受电灯带来的好处，而将电流的奥秘交给工程师去处理。如果你愿意接受耶稣基督成为你个人的救主，请你做这样的祷告：');
INSERT INTO book(chapter,verse,content) VALUES(32,2,'<i>“上帝啊，我实在无法理解救恩的奥秘，</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,3,'<i>也不能明白你为什么顾念我，甚至差遣你</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,4,'<i>的独生子耶稣基督来到世上，为我的罪担</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,5,'<i>当了刑罚。虽然我不明白，但我愿意顺服</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,6,'<i>你。我相信耶稣为我受死，也相信你在《约翰福音》三章 16 节的应许：‘信祂</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,7,'<i>的，不至灭亡，反得永生’。阿门。”（阿门就是诚心所愿的意思。）</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,8,'现在，如果你把生命交托给主耶稣，顺服祂，祂就会进入你的生命。这样，你就可以真诚的');
INSERT INTO book(chapter,verse,content) VALUES(32,9,'说：“主耶稣，我的身、心、灵都要交托给你，我属于你，你也属于我。”');
INSERT INTO book(chapter,verse,content) VALUES(32,10,'如果你已经诚心的做了以上信耶稣的决志祷告，从此以后，你就可以为你的新生命作出下面决志的宣言：');
INSERT INTO book(chapter,verse,content) VALUES(32,11,'<i>“在察验人心的上帝面前，我接受耶稣基</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,12,'<i>督进入我的生命，做我唯一的救主，和生</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,13,'<i>命的主宰。我要完全顺服祂。我知道我已经获得永生，因为《约翰福音》五章 24</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,14,'<i>节说：‘我实实在在的告诉你们，那听我</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,15,'<i>的话、又信差我来者的，就有永生，不至于定罪，是已经出死入生了。’</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,16,'<i>“今天，我进入了 神的家庭，我要像个孝顺的孩子，每天尽力阅读默想 神的话</i>');
INSERT INTO book(chapter,verse,content) VALUES(32,17,'<i>语，每天与我天上的父亲交通祷告。这是我诚心所愿，求 神帮助我。”</i>');
INSERT INTO toc(title) VALUES('第三十三章 一名士兵来到主的跟前');
INSERT INTO book(chapter,verse,content) VALUES(33,1,'我曾经尝试带领一位名叫哈里的年轻士兵接受主耶稣基督，但是，就如许多人一样，他总是以“让我想一想”为借口，来避开这个重要的话题。');
INSERT INTO book(chapter,verse,content) VALUES(33,2,'我对他说：“哈里，让我讲个故事给你听。有一个晚上，你和其他士兵去侦察敌军的营地，在回来的途中，你不幸被敌军打伤。有一位士兵转回头将你背回营地，结果他自己也被两颗子弹打中。后来你们都被送往医院，在医护人员细心的照料下，你们从死亡的魔爪中被救了出来。');
INSERT INTO book(chapter,verse,content) VALUES(33,3,'“两个月后，医生带了一个瘸子来探望你。这瘸子真可怜，他走路时看起来十分痛苦。当他们走到你的床边时，医生便对你说：‘哈里，让我介绍比尔先生给你认识，他就是冒着生命危险搭救你的那个人。’你当时会有什么反应呢？你会不会将双手交叉在胸前，说：‘我不是很肯定要不要见他，让我先想一想吧。’？');
INSERT INTO book(chapter,verse,content) VALUES(33,4,'你当然不会这么做。相反的，你一定会赶紧握住他的手，感激他对你的救命之恩。');
INSERT INTO book(chapter,verse,content) VALUES(33,5,'“现在我要介绍主耶稣基督给你认识，祂不但冒着生命的危险，甚至牺牲了自己的生命来拯救你。你是否会转过身去，说声‘让我想一想’，就不理睬祂了呢？”');
INSERT INTO book(chapter,verse,content) VALUES(33,6,'哈里终于回答说：“不，我愿意接受祂。”接着，我们一起跪下祷告。就在那一刻，他告诉耶稣，愿意接受祂成为他个人的救主。');
INSERT INTO book(chapter,verse,content) VALUES(33,7,'亲爱的朋友，你是否也说‘让我想一想’呢？如果你不谨慎，可能就会将自己永恒排除在 神无比丰盛的恩典之外。你今天应当做的，并且');
INSERT INTO toc(title) VALUES('第三十四章 你要去为神作见证');
INSERT INTO book(chapter,verse,content) VALUES(34,1,'现在我们来到最后，也是最重要的一点。《罗马书》十章 9 到 11 节这么说：“你若口里认耶稣为主，心里相信 神叫祂从死里复活，就必得');
INSERT INTO book(chapter,verse,content) VALUES(34,2,'救。因为人心里相信，就可以称义；口里承认就可以得救。经上说：‘凡信祂的人，必不至于羞愧’。”');
INSERT INTO book(chapter,verse,content) VALUES(34,3,'你说你已经接受了耶稣基督，就应当去告诉别人，不要因为承认耶稣为救主而感到羞耻。');
INSERT INTO book(chapter,verse,content) VALUES(34,4,'有一天，我在码头失足跌入水中，由于受了伤不能游泳，眼看就快要沉溺了。这时，一艘煤炭拖船刚好在附近，船上的一名工人看见了，就急忙跳进水里把我救了上来。一个月后，当我走在街上时，一个满身是肮脏煤炭粉的人，正朝着我走来，我一看就认出他正是那个曾经救了我的工人。这时，我故意转过身去，假装欣赏商店橱窗的摆设，那我就不用停下脚步来');
INSERT INTO book(chapter,verse,content) VALUES(34,5,'向他问安了。如果你看到我这么做，你会把我看成是一个怎样的人呢？');
INSERT INTO book(chapter,verse,content) VALUES(34,6,'既然你已经宣告你相信主耶稣基督为了救你而牺牲祂的生命，在那些轻视主耶稣的人面前，你还会因为祂而感到羞耻，闭口不认祂吗？或是，你会承认祂是你的救主，并在言语行为上荣耀祂的名呢？你既然已经接受了祂，就应当愿意在众人面前承认祂。');
INSERT INTO book(chapter,verse,content) VALUES(34,7,'向别人传扬救主耶稣，是对 神感恩的一种表示！圣诗作者史密斯 (Al Smith) 这么写道：');
INSERT INTO book(chapter,verse,content) VALUES(34,8,'<i>“无论到何处都要述说：主耶稣真好；</i>');
INSERT INTO book(chapter,verse,content) VALUES(34,9,'<i>要让别人知道：主耶稣真好。</i>');
INSERT INTO book(chapter,verse,content) VALUES(34,10,'<i>述说祂的祝福，述说祂的爱，</i>');
INSERT INTO book(chapter,verse,content) VALUES(34,11,'<i>述说祂如何从天上再来；</i>');
INSERT INTO book(chapter,verse,content) VALUES(34,12,'<i>无论到何处都要述说：主耶稣真好。”</i>');
VACUUM;
